#!/bin/bash

# push.sh - 推送 slides 到 GitHub (使用 SSH key，免 token)

set -e

REPO_URL="git@github.com:fatfingererr/slides.git"
COMMIT_MSG="feat: add new slides"

echo "🚀 Pushing slides to GitHub..."

# Check if we're in the slides directory
if [ ! -f "index.html" ]; then
    echo "❌ Error: Please run this script from the slides directory"
    exit 1
fi

# Auto-update index.html with current slides
echo "📝 Updating index.html..."

# Generate slides array from existing HTML files
SLIDES_ARRAY=""
for file in *.html; do
    [ "$file" = "index.html" ] && continue
    
    # Extract date from filename (assumes format: *-slides-YYYY-MM-DD.html)
    date=$(echo "$file" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' || echo "")
    
    # Generate title from filename
    title=$(echo "$file" | sed 's/-slides-.*//; s/-/ /g; s/.html$//')
    title=$(echo "$title" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
    [ -n "$date" ] && title="$title Slides ($date)"
    
    # Add to array
    if [ -z "$SLIDES_ARRAY" ]; then
        SLIDES_ARRAY="{ file: '$file', title: '$title', date: '$date' }"
    else
        SLIDES_ARRAY="$SLIDES_ARRAY,\n            { file: '$file', title: '$title', date: '$date' }"
    fi
done

# Create new index.html with updated slides array
cat > index.html << EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ricky's Slides</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 2rem;
        }
        .container { max-width: 800px; margin: 0 auto; }
        h1 {
            color: white;
            text-align: center;
            margin-bottom: 3rem;
            font-size: 2.5rem;
            text-shadow: 0 2px 10px rgba(0,0,0,0.2);
        }
        .subtitle {
            color: rgba(255,255,255,0.8);
            text-align: center;
            margin-top: -2.5rem;
            margin-bottom: 3rem;
            font-size: 1rem;
        }
        .slides-grid { display: grid; gap: 1rem; }
        .slide-card {
            background: rgba(255,255,255,0.95);
            border-radius: 12px;
            padding: 1.5rem;
            transition: transform 0.2s, box-shadow 0.2s;
            cursor: pointer;
            text-decoration: none;
            color: inherit;
            display: block;
        }
        .slide-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 20px 40px rgba(0,0,0,0.2);
        }
        .slide-title { font-size: 1.25rem; font-weight: 600; color: #333; margin-bottom: 0.5rem; }
        .slide-date { font-size: 0.875rem; color: #666; }
        .empty-state {
            text-align: center;
            color: rgba(255,255,255,0.7);
            padding: 4rem 2rem;
        }
        .footer {
            text-align: center;
            margin-top: 3rem;
            color: rgba(255,255,255,0.6);
            font-size: 0.875rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎤 Slides</h1>
        <p class="subtitle">Generated by content-to-slides</p>
        <div class="slides-grid" id="slidesList"></div>
        <div class="footer">
            <p>Auto-generated from GitHub: fatfingererr/slides</p>
        </div>
    </div>

    <script>
        const slides = [
            $SLIDES_ARRAY
        ];

        const list = document.getElementById('slidesList');
        
        if (slides.length === 0) {
            list.innerHTML = '<div class="empty-state">No slides yet. Check back soon!</div>';
        } else {
            slides.sort((a, b) => new Date(b.date) - new Date(a.date));
            slides.forEach(slide => {
                const card = document.createElement('a');
                card.href = slide.file;
                card.className = 'slide-card';
                card.innerHTML = \`
                    <div class="slide-title"\u003e\${slide.title}</div\u003e
                    <div class="slide-date">📅 \${slide.date}</div\u003e
                \`;
                list.appendChild(card);
            });
        }
    </script>
</body>
</html>
EOF

echo "✅ index.html updated with $(echo "$SLIDES_ARRAY" | tr ',' '\n' | wc -l) slides"

# Add all changes
git add -A

# Check if there are changes to commit
if git diff --cached --quiet; then
    echo "ℹ️ No changes to commit"
    exit 0
fi

# Commit with fixed message
git commit -m "$COMMIT_MSG"

# Push to GitHub using SSH (no token needed if SSH key is configured)
git push origin HEAD:main

echo "✅ Slides pushed successfully!"
echo "🌐 Visit: https://fatfingererr.github.io/slides/"
